### ISSUE TITLE
Animate from 9 to 10

### ISSUE THREAD

**Issue by ayushhgoyal** [adnan-SM/TimelyTextView#17]
Can't we animate from 9 to 10? While doing it an error comes up: java.security.InvalidParameterException: Unsupported number requested

I think this is the most basic functionality, is there some other way of doing it? What am I missing?  

This is how I am doing: 

 holder.sent_count.animate(9, 10).setDuration(500).start();

**Comment by adnan-SM** [comment]
The animation logic supports just 0-9. You should use two views for double digit numbers.
