### ISSUE TITLE
It's on maven ?

### ISSUE THREAD

**Issue by benju69** [adnan-SM/TimelyTextView#19]
What is the dependency ?

**Comment by adnan-SM** [comment]
Its still not published on Maven. I should have some free time in the coming weeks, will have it published then.

**Comment by jitpack-io** [comment]
Why not just release on JitPack? 
It's already working: https://jitpack.io/#adnan-SM/TimelyTextView/29b29716bd

Would be nice to have a GitHub release as well so that it gets a version.

**Comment by adnan-SM** [comment]
Done ! Check the Readme
